version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - y-node-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid"
    image: rails:6.0.3
    volumes:
      - .:/myapp
      - ~/.ssh:/root/.ssh
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      EDITOR: "vi"
    ports:
      - 3000:3000
    networks:
      - y-node-network
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
networks:
  y-node-network:
    external: true
