version: "3.7"

services:
  mysql:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldb:/var/lib/mysql
    networks:
      - y-node-network
  mysql-test:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - y-node-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid"
    image: rails:6.0.3
    volumes:
      - .:/myapp
      - ~/.ssh:/root/.ssh
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      EDITOR: "vi"
    ports:
      - 3000:3000
    networks:
      - y-node-network
    depends_on:
      - mysql
    stdin_open: true
    tty: true
volumes:
  mysqldb:
networks:
  y-node-network:
    external: true
